"""Host-replaceable integration ports for local-path/process capabilities."""

from __future__ import annotations

from typing import Protocol


class CompileExecutor(Protocol):
    def start_compile(
        self,
        project_id: str,
        side: str = "work",
        root_file: str | None = None,
        force: bool = False,
        kind: str = "latexmk",
    ) -> dict: ...

    def start_latexdiff(self, project_id: str, root_file: str | None = None) -> dict: ...
    def get_job(self, project_id: str, job_id: str) -> dict: ...
    def get_pdf_bytes(self, project_id: str, job_id: str | None = None) -> bytes: ...
    def get_log_text(self, project_id: str, job_id: str) -> str: ...
    def get_aux_text(self, project_id: str) -> str: ...
    def get_bbl_text(self, project_id: str) -> str: ...
    def get_tex_context(self, project_id: str) -> dict: ...


class GitBackend(Protocol):
    def archive_refs(
        self,
        repo_url: str,
        base_ref: str,
        revised_ref: str,
        subdir: str | None = None,
    ) -> tuple[bytes, bytes]: ...

    def ensure_repo(self, project_id: str): ...
    def status(self, project_id: str) -> dict: ...
    def log(self, project_id: str, max_count: int = 50, path: str | None = None) -> dict: ...
    def commit(self, project_id: str, message: str, **kwargs) -> dict: ...
    def restore(self, project_id: str, **kwargs) -> dict: ...
    def diff(self, project_id: str, base_ref: str, revised_ref: str) -> dict: ...
    def ls_tree(self, project_id: str, ref: str, **kwargs) -> dict: ...
    def show(self, project_id: str, ref: str, path: str) -> dict: ...
    def show_meta(self, project_id: str, ref: str, path: str) -> dict: ...
    def show_slice(self, project_id: str, ref: str, path: str, **kwargs) -> dict: ...
    def push(self, project_id: str) -> dict: ...
    def zone_from_commit(self, project_id: str, ref: str, name: str | None = None) -> dict: ...
